language: clojure
lein: lein2
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script: lein2 test :all
before_script:
  - psql -c 'create database jdbc_util_test;' -U postgres
env:
  global:
    - JDBCUTIL_DBNAME=//127.0.0.1:5432/jdbc_util_test
    - JDBCUTIL_DBUSER=postgres
    - JDBCUTIL_DBPASS=
addons:
  postgresql: "9.3"
notifications:
  email: false
